### ISSUE TITLE
Error on running  iQvoc as a Rails engine

### ISSUE THREAD

**Issue by geekscruff** [innoq/iqvoc#320]
Followed steps in here: https://github.com/innoq/iqvoc/wiki/iQvoc-as-a-Rails-Engine

On launching localhost:3000

Sass::SyntaxError in Frontpage#index

Undefined variable: "$zindex-modal".

**Comment by mrreynolds** [comment]
We just released iQvoc 4.8.0 with some fixes in the app template. Can you try regenerating your app as documented [here](https://github.com/innoq/iqvoc/wiki/iQvoc-as-a-Rails-Engine)? Please reopen if the problem still occurs.
