### ISSUE TITLE
Concepts without hierarchy

### ISSUE THREAD

**Issue by mrreynolds** [innoq/iqvoc#322]
ATM a concept that has no broader or narrower relations won't get displayed in the hierarchical view. We should introduce a section beneath the tree that lists these concepts.

Bonus: "lost" concepts should be draggable into the tree.

**Comment by mjansing** [comment]
Solved with 94a0add0f312aad45e07d7ac33a076e55f6d85c4. Parentless concepts are now shown in a specific box in the sidebar.
