### ISSUE TITLE
[BUG] compound forms version: changes to existing xl-label don't work

### ISSUE THREAD

**Issue by mgbeyer** [innoq/iqvoc#349]
The modification of a xl-label leads to an error message and the disappearance of the label.

Steps to reproduce faulty behavior:
1) new label (en, but any language will do)
2) enter name (value), e.g. "dummy"
3) save
4) publish
5) new concept
6) preferred labels (en) -> search for "dummy" and pick it
7) save
8) publish
9) navigate to concept
10) navigate to label "dummy" (tab: labels)
11) create new version
12) don't change anything, just save (it doesn't matter if you change stuff)
13) publish

The following message shows up:

Instance has been successfully published.
No permission
Your user account has insufficient permissions to display this page.

Now if you try to look-up the concept, the label "dummy" has disappeared (a closer look into the database confirms this: the concept is still there but there are no entries in the "labels" and "labelings" tables).

The error occurs in the compound forms version only (see https://github.com/innoq/iqvoc_compound_forms). The standard SKOS-XL enabled version seems not to be affected.

**Comment by mgbeyer** [comment]
Well, as I've learned the other day, this is not a specific problem of the CF version. In fact it's rather a database fk contraint problem concerning the skos-xl extension which is addressed by the following commit: https://github.com/innoq/iqvoc_skosxl/commit/486195a18fcce9f82f0efdbeb81599b174f1900d (obviously my particular SKOS-XLversion was slightly older, therefore the strange behavior).

So: case closed I guess :)

**Comment by mjansing** [comment]
No problem. I pushed iqvoc_skosxl v2.7.0 to RubyGems which includes the fix. Thanks
