### ISSUE TITLE
Using downcase for query terms prevents search results for Umlaute 

### ISSUE THREAD

**Issue by fabianzwodrei** [innoq/iqvoc#351]
Most searches iQvoc won't bring up labels with values like "Ägypten" because the .downcase function won't make it a lowercase string.

"Ägypten".downcase => "Ägypten" which is a problem for the sql LOWER(label.value) function that is used for searching. Searching for "Ägypten" will never find "Ägypten" – whereas 'ägypten' will find 'Ägypten' in the DB.

**Comment by mjansing** [comment]
see also #355.

**Comment by mjansing** [comment]
Should be fixed with f440bab. Feel free to reopen if there are any issues.
