### ISSUE TITLE
Sparql Endpoint for UMTHES 

### ISSUE THREAD

**Issue by normansuesstrunk** [innoq/iqvoc#354]
Hello, 

I was trying to find a way to integrate the data / skos concept from the UMTHES website http://data.uba.de/umt/de.html, I want to link some of the concept contained in the UMTHES catalog. I saw that UMTHES uses the IQVoc Software to present the data.  

Is it possible to query a resource (for example http://data.uba.de/umt/_00653011) with a sparql query on a sparql endpoint on http://data.uba.de/umt/de.html? 

I can download the RDF data and store the "localy", but i would prefer to really build a linked application. 

many thanks, 
Norman

**Comment by mjansing** [comment]
Hi,

currently it's not possible to query iQvoc's data using sparql queryl language. But iQvoc provides a sync module to sync data from iQvoc to triple stores and vice versa. Maye this is an option. You can also take a look a iQvoc's API (available inside iQvoc `/apidoc`, e.g. http://try.iqvoc.net/apidoc/)

> I was trying to find a way to integrate the data / skos concept from the UMTHES website http://data.uba.de/umt/de.html...

This is a really old umthes instance providing old data. You might take a look at http://sns.uba.de/umthes/. This would be the upcoming production instance
