### ISSUE TITLE
Duplicate collection assignment on new concept

### ISSUE THREAD

**Issue by metaweidner** [innoq/iqvoc#358]
I am encountering a situation when creating new concepts where a concept is assigned to the same collection multiple times on save. It seems to happen when a Collection and a Concept Mapping are added at the same time. The same collection label appears multiple times on the record after it has been saved. I can either add a Collection and save or add a Concept Mapping and save, but not both at the same time.

**Comment by metaweidner** [comment]
Just saw this commit: 21e51b0
We'll update and see if it fixes the issue.

**Comment by metaweidner** [comment]
We noticed that the 4.10 gem version was released well before the commit to fix the duplicate collection assignment. When do you anticipate a 4.11 release that incorporates this fix?

**Comment by mjansing** [comment]
I pushed v4.11.0 to Rubygems. Let us know if there are any further issues. Thanks for using iQvoc.

**Comment by seanlw** [comment]
I work with @metaweidner and I've been able to replicate the problem under the v4.11 gem. I've provided some screenshots for the process described above. Again, the collection is duplicated only when a Match is added (1 or more). Let me know if you need anything if you can't reproduce.

**Ruby:** 2.2.4 
**Rails:** 4.2.8 
**iQvoc:** 4.11.0

Creating new concept and added "Test Collection" collection:
![screen shot 2017-03-23 at 11 09 22 am](https://cloud.githubusercontent.com/assets/405957/24258064/a2a57184-0fba-11e7-939e-d3a982e25c4e.png)

Match added to concept:
![screen shot 2017-03-23 at 11 09 53 am](https://cloud.githubusercontent.com/assets/405957/24258139/d70cba5e-0fba-11e7-915a-30549c2f9e15.png)

Result showing "Test Collection" added twice after concept is saved:
![screen shot 2017-03-23 at 11 10 01 am](https://cloud.githubusercontent.com/assets/405957/24258175/eee61684-0fba-11e7-9b70-666578d83cb4.png)

**Comment by seanlw** [comment]
If you assign more than one collection, it will duplicate them all.

![screen shot 2017-03-23 at 11 50 58 am](https://cloud.githubusercontent.com/assets/405957/24259531/21d6000a-0fbf-11e7-93aa-a2ab9fa0b398.png)

**Comment by mjansing** [comment]
Thanks for investigation. Yes it looks this is still an issue.

**Comment by mjansing** [comment]
> Again, the collection is duplicated only when a Match is added 

This is a good catch. I'll try to dig into this issue.

**Comment by mjansing** [comment]
@seanlw: I pushed 00c8f27 to deal with this issue. Would you like to test this. After that I'll push iQvoc 4.11.1 to Rubygems.

**Comment by seanlw** [comment]
@mjansing All my tests look good now and I don't see any duplications. Thank you for looking into this so quickly.

**Comment by mjansing** [comment]
Great. I pushed v4.11.1 to Rubygems.
