### ISSUE TITLE
Running iqvoc locally on MAC

### ISSUE THREAD

**Issue by etcware** [innoq/iqvoc#361]
I'm trying to run iqvoc locally, on may MAC. I was able to install only after ruby 2.4.0 installation and I'm using the custom installation. When I run 
```
bundle exec rails s 
```
and then I open my browser on http://localhost:3000/ I get the displayed error. Is it possibile that ruby version is not supported?

<img width="1222" alt="schermata 2017-06-04 alle 19 41 36" src="https://cloud.githubusercontent.com/assets/5634930/26763959/df7bdcce-495d-11e7-8fad-f52a55362900.png">

**Comment by mjansing** [comment]
Oh yes it seems there is a problem. Thank you for this report. iQvoc should run on the most recent ruby version. We take a look at this.

**Comment by ncarboni** [comment]
I had the same problem. Commenting line 2 in rdf_namespaces_helper.rb will make everything run smoothly (very homemade solution though)

**Comment by philippneugebauer** [comment]
@ncarboni Ruby 2.4 is not supported yet due to the Fixnum/Integer class changes made in Ruby 2.4

**Comment by etcware** [comment]
@philippneugebauer this means that iqvoc works with ruby 2.3 without @ncarboni suggested fix?

**Comment by philippneugebauer** [comment]
probably caused by this bugfix: https://bugs.ruby-lang.org/issues/12887

**Comment by mjansing** [comment]
Should be fixed with #363.
