### ISSUE TITLE
Italian language cannot be set as primary

### ISSUE THREAD

**Issue by etcware** [innoq/iqvoc#384]
I selected italian and english as application languages, and then I tried to set italian language as primary, but I received this error:
<img width="1086" alt="schermata 2017-08-06 alle 16 16 04" src="https://user-images.githubusercontent.com/5634930/29004113-9f01c474-7ac2-11e7-8cee-2699b75279db.png">

**Comment by philippneugebauer** [comment]
Since we do not have any italian language file in `config\locales`, I guess that is your problem. You need to provide these translation files before using another language than `DE` or `EN`.

**Comment by etcware** [comment]
ok thank you
