### ISSUE TITLE
Keeping iqvoc updated

### ISSUE THREAD

**Issue by ncarboni** [innoq/iqvoc#386]
Hi, sorry for the very newbie question but I was wondering what was the exact procedure for keeping iqvoc updated. There were recently some issues resolved and I would like to find a way to update without (of course) rebuilding everything.
Can someone point to me to some resources/tutorial/commands?
Thanks in advance!

**Comment by mjansing** [comment]
The best way to run and maintain iQvoc is to run iQvoc as a rails engine. See this for details: https://github.com/innoq/iqvoc/wiki/iQvoc-as-a-Rails-Engine

With this procedure you can change iQvocs version in GEMFILE and use bundler to update dependencies.

Hope that helps.
