### ISSUE TITLE
Customizing Concept Layout

### ISSUE THREAD

**Issue by lbassil** [innoq/iqvoc#387]
Hello,

I need to customize the look and feel of the concept display: http://try.iqvoc.net/en/concepts/air_sports.html

I need to re-order the tabs etc... where are these html files generated and where can I edit the html and css generation of the concepts?

Thank you in advance,
Regards.

**Comment by mjansing** [comment]
Take a look at:

* https://github.com/innoq/iqvoc/tree/master/app/views to find all views (html)
* https://github.com/innoq/iqvoc/tree/master/app/assets/stylesheets here you’ll find corresponding stylesheets (we use SASS as a Stylesheet abstraction)
