### ISSUE TITLE
How to manage multiple vocabularies?

### ISSUE THREAD

**Issue by matteoLorenzini** [innoq/iqvoc#401]
Hi everyone,
I think my question has been already partially  answered by the closed issue #269 . Any update about?
Since I’m going to manage more than one vocabulary the idea should be to use the same instance differentiating the vocabularies by using different path like https://www.myiqvoc.net/first/vocab and https://www.myiqvoc.net/second/vocab 

Is it feasible or not? If yes, what could be the easiest solution for a non sys-admin?
My configuration (if helps):	
Docker image running on port 3000. Reverse proxy via APACHE from http://www.myiqvoc.net:3000 to https://www.myiqvoc.net/

Regards

**Comment by mjansing** [comment]
There is no update. iQvoc is not designed to support mutliple concept schemes.
