### ISSUE TITLE
Problems with running build instructions

### ISSUE THREAD

**Issue by EwaSniegowskaPCSS** [innoq/iqvoc#424]
Hi, I'm trying to run iQvoc according to:
https://github.com/innoq/iqvoc/blob/master/README.md#custom

All previous steps were successfull, but when I call:
`bundle exec rails s`

I get an error:
`ActionView::Template::Error - The manifest file '.../repo/public/assets/manifest.json' is missing`

The message is actually correct, I don't have `manifest.json` or any `assets` folder at all.
When I run iQvoc in docker, there is a folder `assets` (although there is no `manifest.json` there also).
So I'm wondering if I missed some important step?

I tried also to run:
`bundle exec rake assets:precompile`
because it's the step mentioned in Dockerfile which is missing from README.
But it didn't generate `assets` folder.

Do you have some idea what I could be missing?

**Comment by mjansing** [comment]
This instruction is outdated because we switched to a nodejs based asset compilation in the past . I updated instruction with https://github.com/innoq/iqvoc/commit/09ddfba9f5ba0da07d8d1d85dd3bdd8deef2f080.
